server:
  port: 8080
  servlet.context-path: /cli
  error:
    include-message: always
    include-binding-errors: always

management:
  server:
    port: 8088
  endpoints:
    web:
      exposure: health, info, prometheus
  endpoint:
    health:
      show-details: always

env: ${APP_ENV:local}

spring:
  config:
    import: optional:file:.env[.properties]
  application.name: cli
  profiles.active: local
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fb}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: false
          use_sql_comments: false
      jackson:
        default-property-inclusion: non_null
        serialization.write-dates-as-timestamps: false
      liquibase:
        default-schema: facebook_crawler
        enabled: ${LIQUIBASE_ENABLED:true}
        change-log: classpath:/db/changelog/db.changelog.xml

okhttp:
  connect-timeout: 10s
  read-timeout: 30s
  write-timeout: 30s
  call-timeout: 0s
  ping-interval: 0s
  retry-on-connection-failure: true
  follow-redirects: true
  follow-ssl-redirects: true
  connection-pool:
    max-idle-connections: 10
    keep-alive-duration: 5m

---
async.executor:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 100
  thread-name-prefix: async-
---
logging:
  level:
    com.facebook.collector: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
  config: classpath:logback/logback-${env}.xml